package com.senkurye.courier.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity representing an automated Dispatch Assignment linking a Courier to an Order.
 * Reflects the core business rule: "Kurye siparişi kabul veya reddedemez".
 * Automatically placed into the courier's active queue and optimized route.
 */
@Entity(
    tableName = "assignments",
    indices = [
        Index(value = ["orderId"], unique = true),
        Index(value = ["courierId"]),
        Index(value = ["status"]),
        Index(value = ["sequenceNumber"])
    ]
)
data class AssignmentEntity(
    @PrimaryKey
    val id: String, // Unique assignment ID generated by backend dispatch engine
    val orderId: String,
    val courierId: String,
    val assignedAt: Long = System.currentTimeMillis(),
    val status: String, // ASSIGNED, AT_RESTAURANT, PICKED_UP, ON_ROUTE, DELIVERED, CANCELLED
    val sequenceNumber: Int, // Route optimization order
    val estimatedPickupTime: Long? = null,
    val estimatedDeliveryTime: Long? = null,
    val actualPickupTime: Long? = null,
    val actualDeliveryTime: Long? = null,
    val routeCostScore: Double = 0.0,
    val isAutoAssigned: Boolean = true,
    val isSynced: Boolean = true,
    val idempotencyKey: String = ""
)
